- name: Provision Receptor
  remote_user: ubuntu
  hosts: tag_Type_receptor
  vars:
    plex_dir: /opt/local/plex
  tasks:
    - name: Install aptitude
      become: yes
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Create required  directories, writable by user
      become: yes
      ansible.builtin.file:
        path: "{{ item }}"
        owner: ubuntu
        group: ubuntu 
        state: directory
      loop:
        - "{{ plex_dir }}"
        - /opt/local/receptor

    - name: Ensure env file exists
      ansible.builtin.file:
        path: /opt/local/receptor/env
        state: touch

    - name: Pull the plex repository
      ansible.builtin.git:
        repo: https://github.com/labdao/plex.git
        dest: "{{ plex_dir }}/"
        version: ops/receptor

    - name: Install system packages
      become: yes
      ansible.builtin.apt:
        pkg:
          - golang-go
